In [10]:
import numpy as np
distance= np.array([10, 20, 30])
time=np.array([2, 3, 4])
s = distance / time
print(s) 
type(s)

[5.         6.66666667 7.5       ]


numpy.ndarray

In [5]:
#we need array because list doesnot perform this function but array can

In [11]:
import numpy as np

In [13]:
l=[[1,2,3],[2,3,4],[3,4,5]]
arr=np.array(l)
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [14]:
arr[2][1] #indexing

4

In [16]:
arr.ndim #to check the dimension 

2

In [19]:
arr.shape #it give output in tuple

(3, 3)

In [20]:
arr.shape[0] #we can also do indexing in tuple

3

In [21]:
arr.size #total elements in an array

9

In [22]:
arr.dtype 

dtype('int32')

In [23]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [33]:
a=np.array([[1,2],[3,4]])
b=2*a
b


array([[2, 4],
       [6, 8]])

In [34]:
print(a)

[[1 2]
 [3 4]]


In [5]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [7]:
arr[1][1]=50

In [8]:
arr #yes array is mutible in nature

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [9]:
arr=np.array(arr,dtype=float) #to change in float

In [10]:
arr

array([[ 1.,  2.,  3.],
       [ 4., 50.,  6.],
       [ 7.,  8.,  9.]])

In [11]:
arr=np.array([[90,86,67,55,49],[89,34,45,78,86]])

In [12]:
arr

array([[90, 86, 67, 55, 49],
       [89, 34, 45, 78, 86]])

In [13]:
passing_marks=50

In [14]:
arr>passing_marks

array([[ True,  True,  True,  True, False],
       [ True, False, False,  True,  True]])

In [15]:
arr[arr>passing_marks]

array([90, 86, 67, 55, 89, 78, 86])

#wap to create two arrays of distance covered by 2 cycle , add then up to the total distance covered .if the distance is greater then 30 filter those values only ..shape 1X3

In [21]:
cycle1=np.array([34,56,7])
cycle2=np.array([52,46,21])
cycle=cycle1+cycle2

In [22]:
cycle

array([ 86, 102,  28])

In [23]:
distance_covered =30

In [24]:
cycle>distance_covered

array([ True,  True, False])

In [25]:
cycle[cycle>distance_covered]

array([ 86, 102])

In [26]:
s=np.array([["delhi","mumbai","pune","indore","chennai"],["delhi","maha","Maha","mp","tn"]])

In [27]:
s

array([['delhi', 'mumbai', 'pune', 'indore', 'chennai'],
       ['delhi', 'maha', 'Maha', 'mp', 'tn']], dtype='<U7')

In [28]:
s[0:2,1:3]

array([['mumbai', 'pune'],
       ['maha', 'Maha']], dtype='<U7')

In [29]:
s[:,3:5]

array([['indore', 'chennai'],
       ['mp', 'tn']], dtype='<U7')

In [34]:
s[:,3:5][1][0]

'mp'

In [35]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

wap tp create a 3X3 array then slice it as we want 1 and 2 row ,1 and 2 column after sliceing which element of slice array are divisible by 3

In [39]:
b=a[1:3,1:3]

In [42]:
b%3==0

array([[False,  True],
       [False,  True]])

In [43]:
b[b%3==0]

array([6, 9])

In [45]:
b[b%3==0].ipynb_checkpoints/sum() #add the no wo satisfy the conditions

15

In [46]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [56]:
l=[]
for i in a:
    for j in i:
        l.append(j)

In [57]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
a=np.array([[[1,2,3,4,5,6,7,8,9,10]]])
a[0][0][0] #for slicing and indexing method 

1

In [1]:
import numpy as np

# universal functions

In [4]:
a=np.array([1,4,9,16,25,36,49,64,81,100])
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [6]:
np.sin(a) #taking value as angle

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175,
       -0.99177885, -0.95375265,  0.92002604, -0.62988799, -0.50636564])

In [8]:
np.sqrt(a)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
np.cos(a)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948,  0.99120281,
       -0.12796369,  0.30059254,  0.39185723,  0.77668598,  0.86231887])

In [10]:
np.exp(a)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10, 4.31123155e+15, 1.90734657e+21, 6.23514908e+27,
       1.50609731e+35, 2.68811714e+43])

In [11]:
np.log(a)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582,
       3.58351894, 3.8918203 , 4.15888308, 4.39444915, 4.60517019])

In [17]:
from numpy import pi

In [18]:
np.sin(pi/2)

1.0

In [19]:
np.cos(pi/4)

0.7071067811865476

In [20]:
#floor and ceiling 

In [21]:
a=np.array([12.45,3.23,15.67,-9.17])
np.floor(a) #in floor it take the lower value

array([ 12.,   3.,  15., -10.])

In [22]:
np.ceil(a) #it take the highest value

array([13.,  4., 16., -9.])

#shape manipulation :- to change the shape of matrix

1) reshape :-it give new array (orignal array doesnot change)
2) resize :- orignal array also change
3) ravel :- it convert it into 1d array
4) flatten :- it alsp convert the array into 1dim

In [27]:
arr=np.array([1,2,3,4,5,6,7,8,9])
np.reshape(arr,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr=np.array([1,2,3,4,5,6,7,8,9])
np.reshape(arr,(9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [26]:
arr=np.array([1,2,3,4,5,6,7,8,9])
np.resize(arr,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [33]:
a.resize(2,3)

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a=np.array([[1,2,3],[4,5,6]])

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.ravel(a) #it change the array in 1dimesion ...but orignal raay doesnot change

array([1, 2, 3, 4, 5, 6])

In [39]:
b=a.flatten()

In [40]:
b

array([1, 2, 3, 4, 5, 6])

# lambda a,b:a+b #in lambda we take parameter and also take logic 

In [50]:
c=lambda a,b:a+b
c(10,20)

30

In [54]:
a=lambda c:(9/5*c)+32
a(0)

32.0

In [53]:
b=lambda a,b:a**b
b(10,2)

100

# from function

In [55]:
np.fromfunction(lambda x,y:x+y,(4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

# fromiter

In [61]:
np.fromiter([1,2,3,4,5],dtype= float )

array([1., 2., 3., 4., 5.])

# fromstring

In [62]:
np.fromstring("1 2 3 4 5 6 7 8 9 10",sep =" ", dtype=int) #always take no otherwise it doesnot support

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# arrays of zero

In [66]:
a=np.zeros((3,3))

In [67]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
b=np.ones((3,3))

In [69]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
a/b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [79]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
np.diag(a,k=0) #too see the value of diag

array([1, 5, 9])

In [84]:
np.tri(3,k=1) #above the diag all value are zero and below the value are1...

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [85]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [90]:
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [91]:
np.diagflat([1,2,3]) #we can add value in diag according to uss...

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [2]:
import numpy as np
np.arange(11.2,2,-1.2) #in arange it also take float value

array([11.2, 10. ,  8.8,  7.6,  6.4,  5.2,  4. ,  2.8])

In [3]:
np.linspace(1,10,20) #we take 1 to 10 in 20 steps so it automatically calculates the difference and give the output

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [4]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.trace(a) #to sum of the diagnol value

15

In [9]:
from numpy import random

In [10]:
a=np.random.rand(3,3) #rand always create array btw 0 to 1

In [11]:
a

array([[0.62589143, 0.05514195, 0.66489491],
       [0.46415053, 0.20636047, 0.40974418],
       [0.52489748, 0.58621739, 0.22410214]])

In [15]:
np.shape(a)

(3, 3)

In [16]:
b=np.random.randint(1,100,(5,5)) #randint will take any no but it give random no
b

array([[46, 55, 96,  9, 94],
       [ 2, 51,  8, 47, 25],
       [81, 31, 45, 33, 96],
       [75, 49, 91,  1,  5],
       [38, 30,  7, 53, 30]])

In [19]:
np.random.randn(4,4)

array([[ 1.36337875, -0.21936671, -0.73768516, -0.50522988],
       [ 0.08777885,  0.50485795, -0.33612844,  0.12385268],
       [ 0.2732822 , -0.44919491,  0.97470107,  1.42612683],
       [-0.19067804, -0.50171701,  0.94655214, -0.12221934]])

In [27]:
a=np.array([[1,2,4],[5,3,7],[9,8,6]])
a

array([[1, 2, 4],
       [5, 3, 7],
       [9, 8, 6]])

In [29]:
a.sort(axis=0)
a

array([[1, 2, 4],
       [3, 5, 7],
       [6, 8, 9]])

In [30]:
a.max()

9

In [31]:
a.min()

1

In [34]:
np.argmax(a,axis=1)

array([2, 2, 2], dtype=int64)

In [37]:
np.argmax(a)

8

In [38]:
np.argmin(a)

0

In [39]:
np.cumsum([1,2,3,4,5,6,7,8,9])

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [41]:
np.cumsum([[1,2,3],[4,5,6]])

array([ 1,  3,  6, 10, 15, 21], dtype=int32)